import React from 'react';
import './TermsAndConditions.css'; // Import the CSS file

const TermsAndConditions: React.FC = () => {
  return (
    <div className="terms-container">
      <h1>Terms & Conditions</h1>

      <p>
        This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as
        applicable and the amended provisions pertaining to electronic records in various statutes. This record is
        generated by a computer system and does not require any physical or digital signatures.
      </p>

      <p>
        This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries
        Guidelines) Rules, 2011 that requires publishing the rules and regulations, privacy policy, and Terms of Use
        for accessing or using the domain name <strong>myurbankicks.in</strong> ("Platform").
      </p>

      <p>
        The Platform is owned by URBAN KICKS, a company incorporated under the Companies Act, 1956 with its registered
        office at Sainagar, Arvi, Wardha (hereinafter referred to as "Platform Owner", "we", "us", "our").
      </p>

      <ol>
        <li>
          <h2>Acceptance of Terms</h2>
          <p>
            Your use of the Platform and services/tools are governed by these Terms of Use. By accessing the Platform,
            you accept these terms, along with our privacy policy and any other applicable service conditions.
          </p>
        </li>

        <li>
          <h2>User Obligations</h2>
          <ul>
            <li>You agree to provide accurate and complete information during registration.</li>
            <li>You are responsible for maintaining confidentiality of your account and password.</li>
            <li>
              You agree to accept responsibility for all activities under your account and follow applicable laws at all
              times.
            </li>
          </ul>
        </li>

        <li>
          <h2>Content Ownership</h2>
          <p>
            All content on this Platform is either owned by or licensed to URBAN KICKS. Unauthorized use of any content
            may lead to a claim for damages and/or be a criminal offense.
          </p>
        </li>

        <li>
          <h2>Prohibited Use</h2>
          <ul>
            <li>You must not misuse the Platform by introducing viruses, trojans, or other harmful material.</li>
            <li>You must not attempt unauthorized access to any part of the Platform.</li>
            <li>You must not use our content or name for commercial purposes without permission.</li>
          </ul>
        </li>

        <li>
          <h2>Third-Party Links</h2>
          <p>
            The Platform may include links to third-party websites. We are not responsible for the content or privacy
            practices of these sites. Use them at your own discretion.
          </p>
        </li>

        <li>
          <h2>Contractual Relationship</h2>
          <p>
            Any purchase, registration, or engagement on the Platform constitutes a legally binding agreement with
            URBAN KICKS, and you agree to the applicable policies and procedures.
          </p>
        </li>

        <li>
          <h2>Indemnity</h2>
          <p>
            You agree to indemnify and hold harmless URBAN KICKS, its affiliates, officers, agents, and employees from
            any claims or demands arising out of your breach of these Terms or violation of any law or third-party
            rights.
          </p>
        </li>

        <li>
          <h2>Force Majeure</h2>
          <p>
            We are not liable for any failure or delay in performance due to causes beyond our reasonable control,
            including natural disasters, war, strikes, and governmental actions.
          </p>
        </li>

        <li>
          <h2>Governing Law & Jurisdiction</h2>
          <p>
            These Terms are governed by Indian laws. Any dispute arising shall be subject to the exclusive jurisdiction
            of courts in Wardha, Maharashtra.
          </p>
        </li>

        <li>
          <h2>Contact</h2>
          <p>
            For any questions or concerns, please reach out via the contact information provided on our website. We are
            available Monday to Friday, 9:00 AM – 6:00 PM.
          </p>
        </li>
      </ol>
    </div>
  );
};

export default TermsAndConditions;
